trigger:
- main

pool: Ubuntu latest


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  # inputs: 
- script : sudo apt-get install mono-complete
- script: |
    export PATH=$PATH:/usr/bin/mono
      
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    # projects: '$(solution)'
    # arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    # projects: '$(solution)'
    # arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    # projects: '$(solution)'
    # arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    # pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'